/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Peter_D (https://sketchfab.com/better_peter)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mercedes-e-class-w212-119c5e10733142b197aa53b86f6aeb04
title: Mercedes E Class W212
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/carModel.gltf");
  const { actions } = useAnimations(animations, group);

  return (
    <>
      <group ref={group} {...props} dispose={null}>
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="fbx_mergefbx" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_2">
                <group name="RootNode">
                  <group name="Root" rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="Body" position={[0, 0, 0.2]}>
                      <group name="DoorFL" position={[-0.91, 0.89, 0.54]}>
                        <group name="mesh_DoorFL">
                          <group
                            name="Object_24"
                            position={[0.91, -1.16, -0.03]}
                          >
                            <mesh
                              name="mesh_DoorFL_mat_rubber_0"
                              geometry={nodes.mesh_DoorFL_mat_rubber_0.geometry}
                              material={materials.mat_rubber}
                            />
                            <mesh
                              name="mesh_DoorFL_mat_glass_0"
                              geometry={nodes.mesh_DoorFL_mat_glass_0.geometry}
                              material={materials.mat_glass}
                            />
                            <mesh
                              name="mesh_DoorFL_mat_plastic_0"
                              geometry={
                                nodes.mesh_DoorFL_mat_plastic_0.geometry
                              }
                              material={materials.mat_plastic}
                            />
                            <mesh
                              name="mesh_DoorFL_mat_chrome_0"
                              geometry={nodes.mesh_DoorFL_mat_chrome_0.geometry}
                              material={materials.mat_chrome}
                            />
                            <mesh
                              name="mesh_DoorFL_mat_lights_0"
                              geometry={nodes.mesh_DoorFL_mat_lights_0.geometry}
                              material={materials.mat_lights}
                            />
                            <mesh
                              name="mesh_DoorFL_mat_leather_0"
                              geometry={
                                nodes.mesh_DoorFL_mat_leather_0.geometry
                              }
                              material={materials.mat_leather}
                            />
                            <mesh
                              name="mesh_DoorFL_mat_inside_panel_0"
                              geometry={
                                nodes.mesh_DoorFL_mat_inside_panel_0.geometry
                              }
                              material={materials.mat_inside_panel}
                            />
                            <mesh
                              name="mesh_DoorFL_mat_salon_0"
                              geometry={nodes.mesh_DoorFL_mat_salon_0.geometry}
                              material={materials.mat_salon}
                            />
                            <mesh
                              name="mesh_DoorFL_mat_body_0"
                              geometry={nodes.mesh_DoorFL_mat_body_0.geometry}
                              material={materials.mat_body}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="DoorFR" position={[0.91, 0.89, 0.54]}>
                        <group name="mesh_DoorFR">
                          <group
                            name="Object_36"
                            position={[-0.91, -1.16, -0.03]}
                          >
                            <mesh
                              name="mesh_DoorFR_mat_body_0"
                              geometry={nodes.mesh_DoorFR_mat_body_0.geometry}
                              material={materials.mat_body}
                            />
                            <mesh
                              name="mesh_DoorFR_mat_rubber_0"
                              geometry={nodes.mesh_DoorFR_mat_rubber_0.geometry}
                              material={materials.mat_rubber}
                            />
                            <mesh
                              name="mesh_DoorFR_mat_glass_0"
                              geometry={nodes.mesh_DoorFR_mat_glass_0.geometry}
                              material={materials.mat_glass}
                            />
                            <mesh
                              name="mesh_DoorFR_mat_plastic_0"
                              geometry={
                                nodes.mesh_DoorFR_mat_plastic_0.geometry
                              }
                              material={materials.mat_plastic}
                            />
                            <mesh
                              name="mesh_DoorFR_mat_chrome_0"
                              geometry={nodes.mesh_DoorFR_mat_chrome_0.geometry}
                              material={materials.mat_chrome}
                            />
                            <mesh
                              name="mesh_DoorFR_mat_lights_0"
                              geometry={nodes.mesh_DoorFR_mat_lights_0.geometry}
                              material={materials.mat_lights}
                            />
                            <mesh
                              name="mesh_DoorFR_mat_leather_0"
                              geometry={
                                nodes.mesh_DoorFR_mat_leather_0.geometry
                              }
                              material={materials.mat_leather}
                            />
                            <mesh
                              name="mesh_DoorFR_mat_inside_panel_0"
                              geometry={
                                nodes.mesh_DoorFR_mat_inside_panel_0.geometry
                              }
                              material={materials.mat_inside_panel}
                            />
                            <mesh
                              name="mesh_DoorFR_mat_salon_0"
                              geometry={nodes.mesh_DoorFR_mat_salon_0.geometry}
                              material={materials.mat_salon}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="DoorRL" position={[-0.9, -0.25, 0.34]}>
                        <group name="mesh_DoorRL">
                          <group name="Object_48" position={[0.9, -0.02, 0.17]}>
                            <mesh
                              name="mesh_DoorRL_mat_rubber_0"
                              geometry={nodes.mesh_DoorRL_mat_rubber_0.geometry}
                              material={materials.mat_rubber}
                            />
                            <mesh
                              name="mesh_DoorRL_mat_glass_0"
                              geometry={nodes.mesh_DoorRL_mat_glass_0.geometry}
                              material={materials.mat_glass}
                            />
                            <mesh
                              name="mesh_DoorRL_mat_plastic_0"
                              geometry={
                                nodes.mesh_DoorRL_mat_plastic_0.geometry
                              }
                              material={materials.mat_plastic}
                            />
                            <mesh
                              name="mesh_DoorRL_mat_chrome_0"
                              geometry={nodes.mesh_DoorRL_mat_chrome_0.geometry}
                              material={materials.mat_chrome}
                            />
                            <mesh
                              name="mesh_DoorRL_mat_leather_0"
                              geometry={
                                nodes.mesh_DoorRL_mat_leather_0.geometry
                              }
                              material={materials.mat_leather}
                            />
                            <mesh
                              name="mesh_DoorRL_mat_inside_panel_0"
                              geometry={
                                nodes.mesh_DoorRL_mat_inside_panel_0.geometry
                              }
                              material={materials.mat_inside_panel}
                            />
                            <mesh
                              name="mesh_DoorRL_mat_salon_0"
                              geometry={nodes.mesh_DoorRL_mat_salon_0.geometry}
                              material={materials.mat_salon}
                            />
                            <mesh
                              name="mesh_DoorRL_mat_body_0"
                              geometry={nodes.mesh_DoorRL_mat_body_0.geometry}
                              material={materials.mat_body}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="DoorRR" position={[0.9, -0.25, 0.34]}>
                        <group name="mesh_DoorRR">
                          <group
                            name="Object_59"
                            position={[-0.9, -0.02, 0.17]}
                          >
                            <mesh
                              name="mesh_DoorRR_mat_body_0"
                              geometry={nodes.mesh_DoorRR_mat_body_0.geometry}
                              material={materials.mat_body}
                            />
                            <mesh
                              name="mesh_DoorRR_mat_rubber_0"
                              geometry={nodes.mesh_DoorRR_mat_rubber_0.geometry}
                              material={materials.mat_rubber}
                            />
                            <mesh
                              name="mesh_DoorRR_mat_glass_0"
                              geometry={nodes.mesh_DoorRR_mat_glass_0.geometry}
                              material={materials.mat_glass}
                            />
                            <mesh
                              name="mesh_DoorRR_mat_plastic_0"
                              geometry={
                                nodes.mesh_DoorRR_mat_plastic_0.geometry
                              }
                              material={materials.mat_plastic}
                            />
                            <mesh
                              name="mesh_DoorRR_mat_chrome_0"
                              geometry={nodes.mesh_DoorRR_mat_chrome_0.geometry}
                              material={materials.mat_chrome}
                            />
                            <mesh
                              name="mesh_DoorRR_mat_leather_0"
                              geometry={
                                nodes.mesh_DoorRR_mat_leather_0.geometry
                              }
                              material={materials.mat_leather}
                            />
                            <mesh
                              name="mesh_DoorRR_mat_inside_panel_0"
                              geometry={
                                nodes.mesh_DoorRR_mat_inside_panel_0.geometry
                              }
                              material={materials.mat_inside_panel}
                            />
                            <mesh
                              name="mesh_DoorRR_mat_salon_0"
                              geometry={nodes.mesh_DoorRR_mat_salon_0.geometry}
                              material={materials.mat_salon}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="Hood" position={[0, 0.85, 0.74]}>
                        <group name="mesh_Hood">
                          <group name="Object_70" position={[0, -1.12, -0.23]}>
                            <mesh
                              name="mesh_Hood_mat_body_0"
                              geometry={nodes.mesh_Hood_mat_body_0.geometry}
                              material={materials.mat_body}
                            />
                            <mesh
                              name="mesh_Hood_mat_plastic_0"
                              geometry={nodes.mesh_Hood_mat_plastic_0.geometry}
                              material={materials.mat_plastic}
                            />
                            <mesh
                              name="mesh_Hood_mat_chrome_0"
                              geometry={nodes.mesh_Hood_mat_chrome_0.geometry}
                              material={materials.mat_chrome}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="Trunk" position={[0, -1.8, 0.83]}>
                        <group name="mesh_Trunk">
                          <group name="Object_76" position={[0, 1.53, -0.31]}>
                            <mesh
                              name="mesh_Trunk_mat_plastic_0"
                              geometry={nodes.mesh_Trunk_mat_plastic_0.geometry}
                              material={materials.mat_plastic}
                            />
                            <mesh
                              name="mesh_Trunk_mat_chrome_0"
                              geometry={nodes.mesh_Trunk_mat_chrome_0.geometry}
                              material={materials.mat_chrome}
                            />
                            <mesh
                              name="mesh_Trunk_mat_lights_glass_0"
                              geometry={
                                nodes.mesh_Trunk_mat_lights_glass_0.geometry
                              }
                              material={materials.mat_lights_glass}
                            />
                            <mesh
                              name="mesh_Trunk_mat_lights_glass2_0"
                              geometry={
                                nodes.mesh_Trunk_mat_lights_glass2_0.geometry
                              }
                              material={materials.mat_lights_glass2}
                            />
                            <mesh
                              name="mesh_Trunk_mat_lights_0"
                              geometry={nodes.mesh_Trunk_mat_lights_0.geometry}
                              material={materials.mat_lights}
                            />
                            <mesh
                              name="mesh_Trunk_mat_body_0"
                              geometry={nodes.mesh_Trunk_mat_body_0.geometry}
                              material={materials.mat_body}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="BrakeFL" position={[-0.77, 1.48, 0.13]}>
                        <group name="mesh_BrakeFL">
                          <group name="Object_8" position={[0.77, -1.75, 0.38]}>
                            <mesh
                              name="mesh_BrakeFL_mat_brakes_0"
                              geometry={
                                nodes.mesh_BrakeFL_mat_brakes_0.geometry
                              }
                              material={materials.mat_brakes}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="BrakeFR" position={[0.77, 1.48, 0.13]}>
                        <group name="mesh_BrakeFR">
                          <group
                            name="Object_12"
                            position={[-0.77, -1.75, 0.38]}
                          >
                            <mesh
                              name="mesh_BrakeFR_mat_brakes_0"
                              geometry={
                                nodes.mesh_BrakeFR_mat_brakes_0.geometry
                              }
                              material={materials.mat_brakes}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="BrakeRL" position={[-0.77, -1.38, 0.13]}>
                        <group name="mesh_BrakeRL">
                          <group name="Object_16" position={[0.77, 1.12, 0.4]}>
                            <mesh
                              name="mesh_BrakeRL_mat_brakes_0"
                              geometry={
                                nodes.mesh_BrakeRL_mat_brakes_0.geometry
                              }
                              material={materials.mat_brakes}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="BrakeRR" position={[0.77, -1.38, 0.13]}>
                        <group name="mesh_BrakeRR" position={[0, 0, -0.02]}>
                          <group name="Object_20" position={[-0.77, 1.12, 0.4]}>
                            <mesh
                              name="mesh_BrakeRR_mat_brakes_0"
                              geometry={
                                nodes.mesh_BrakeRR_mat_brakes_0.geometry
                              }
                              material={materials.mat_brakes}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="WheelFL" position={[-0.77, 1.48, 0.13]}>
                        <group name="mesh_WheelFL">
                          <group
                            name="Object_85"
                            position={[0.77, -1.75, 0.38]}
                          >
                            <mesh
                              name="mesh_WheelFL_mat_wheels_0"
                              geometry={
                                nodes.mesh_WheelFL_mat_wheels_0.geometry
                              }
                              material={materials.mat_wheels}
                            />
                            <mesh
                              name="mesh_WheelFL_mat_tires_0"
                              geometry={nodes.mesh_WheelFL_mat_tires_0.geometry}
                              material={materials.mat_tires}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="WheelFR" position={[0.77, 1.48, 0.13]}>
                        <group name="mesh_WheelFR">
                          <group
                            name="Object_90"
                            position={[-0.77, -1.75, 0.38]}
                          >
                            <mesh
                              name="mesh_WheelFR_mat_wheels_0"
                              geometry={
                                nodes.mesh_WheelFR_mat_wheels_0.geometry
                              }
                              material={materials.mat_wheels}
                            />
                            <mesh
                              name="mesh_WheelFR_mat_tires_0"
                              geometry={nodes.mesh_WheelFR_mat_tires_0.geometry}
                              material={materials.mat_tires}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="WheelRL" position={[-0.77, -1.38, 0.13]}>
                        <group name="mesh_WheelRR" position={[-0.03, 0, 0]}>
                          <group name="Object_95" position={[0.8, 1.12, 0.4]}>
                            <mesh
                              name="mesh_WheelRR_mat_wheels_0"
                              geometry={
                                nodes.mesh_WheelRR_mat_wheels_0.geometry
                              }
                              material={materials.mat_wheels}
                            />
                            <mesh
                              name="mesh_WheelRR_mat_tires_0"
                              geometry={nodes.mesh_WheelRR_mat_tires_0.geometry}
                              material={materials.mat_tires}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="WheelRR" position={[0.77, -1.38, 0.13]}>
                        <group name="mesh_WheelRR_1" position={[0.03, 0, 0]}>
                          <group name="Object_100" position={[-0.8, 1.12, 0.4]}>
                            <mesh
                              name="mesh_WheelRR_mat_wheels_0_1"
                              geometry={
                                nodes.mesh_WheelRR_mat_wheels_0_1.geometry
                              }
                              material={materials.mat_wheels}
                            />
                            <mesh
                              name="mesh_WheelRR_mat_tires_0_1"
                              geometry={
                                nodes.mesh_WheelRR_mat_tires_0_1.geometry
                              }
                              material={materials.mat_tires}
                            />
                          </group>
                        </group>
                      </group>
                      <group
                        name="Wipper1"
                        position={[-0.67, 0.93, 0.72]}
                        rotation={[-0.49, -0.07, 0.08]}
                      >
                        <group name="mesh_Wipper1">
                          <group
                            name="Object_105"
                            position={[0.54, -1, -0.79]}
                            rotation={[0.49, 0.02, -0.1]}
                          >
                            <mesh
                              name="mesh_Wipper1_mat_plastic_0"
                              geometry={
                                nodes.mesh_Wipper1_mat_plastic_0.geometry
                              }
                              material={materials.mat_plastic}
                            />
                          </group>
                        </group>
                      </group>
                      <group
                        name="Wipper2"
                        position={[0.03, 1, 0.78]}
                        rotation={[-0.28, 0.05, -0.06]}
                      >
                        <group
                          name="Wipper2_1"
                          position={[0.04, 0.11, -0.02]}
                          rotation={[-0.14, 0, 0]}
                        >
                          <group name="mesh_Wipper2_1">
                            <group
                              name="Object_110"
                              position={[0.04, -1.15, -0.76]}
                              rotation={[0.43, -0.03, 0.08]}
                            >
                              <mesh
                                name="mesh_Wipper2_1_mat_plastic_0"
                                geometry={
                                  nodes.mesh_Wipper2_1_mat_plastic_0.geometry
                                }
                                material={materials.mat_plastic}
                              />
                            </group>
                          </group>
                        </group>
                        <group
                          name="Wipper2_2"
                          position={[0.2, 0.09, 0]}
                          rotation={[0, 0.11, 0.08]}
                        >
                          <group name="mesh_Wipper2_2">
                            <group
                              name="Object_114"
                              position={[-0.15, -1.21, -0.61]}
                              rotation={[0.28, -0.16, 0.03]}
                            >
                              <mesh
                                name="mesh_Wipper2_2_mat_plastic_0"
                                geometry={
                                  nodes.mesh_Wipper2_2_mat_plastic_0.geometry
                                }
                                material={materials.mat_plastic}
                              />
                            </group>
                          </group>
                        </group>
                        <group name="mesh_Wipper2">
                          <group
                            name="Object_117"
                            position={[0.07, -1.14, -0.61]}
                            rotation={[0.28, -0.03, 0.08]}
                          >
                            <mesh
                              name="mesh_Wipper2_mat_plastic_0"
                              geometry={
                                nodes.mesh_Wipper2_mat_plastic_0.geometry
                              }
                              material={materials.mat_plastic}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="mesh_Body">
                        <group name="Object_120" position={[0, -0.27, 0.51]}>
                          <mesh
                            name="mesh_Body_mat_body_0"
                            geometry={nodes.mesh_Body_mat_body_0.geometry}
                            material={materials.mat_body}
                          />
                          <mesh
                            name="mesh_Body_mat_bottom_0"
                            geometry={nodes.mesh_Body_mat_bottom_0.geometry}
                            material={materials.mat_bottom}
                          />
                          <mesh
                            name="mesh_Body_mat_glass_0"
                            geometry={nodes.mesh_Body_mat_glass_0.geometry}
                            material={materials.mat_glass}
                          />
                          <mesh
                            name="mesh_Body_mat_plastic_0"
                            geometry={nodes.mesh_Body_mat_plastic_0.geometry}
                            material={materials.mat_plastic}
                          />
                          <mesh
                            name="mesh_Body_mat_chrome_0"
                            geometry={nodes.mesh_Body_mat_chrome_0.geometry}
                            material={materials.mat_chrome}
                          />
                          <mesh
                            name="mesh_Body_mat_lights_glass_0"
                            geometry={
                              nodes.mesh_Body_mat_lights_glass_0.geometry
                            }
                            material={materials.mat_lights_glass}
                          />
                          <mesh
                            name="mesh_Body_mat_lights_glass2_0"
                            geometry={
                              nodes.mesh_Body_mat_lights_glass2_0.geometry
                            }
                            material={materials.mat_lights_glass2}
                          />
                          <mesh
                            name="mesh_Body_mat_lights_0"
                            geometry={nodes.mesh_Body_mat_lights_0.geometry}
                            material={materials.mat_lights}
                          />
                          <mesh
                            name="mesh_Body_mat_inside_gauges_0"
                            geometry={
                              nodes.mesh_Body_mat_inside_gauges_0.geometry
                            }
                            material={materials.mat_inside_gauges}
                          />
                          <mesh
                            name="mesh_Body_mat_leather_0"
                            geometry={nodes.mesh_Body_mat_leather_0.geometry}
                            material={materials.mat_leather}
                          />
                          <mesh
                            name="mesh_Body_mat_inside_panel_0"
                            geometry={
                              nodes.mesh_Body_mat_inside_panel_0.geometry
                            }
                            material={materials.mat_inside_panel}
                          />
                          <mesh
                            name="mesh_Body_mat_salon_0"
                            geometry={nodes.mesh_Body_mat_salon_0.geometry}
                            material={materials.mat_salon}
                          />
                          <mesh
                            name="mesh_Body_mat_rubber_0"
                            geometry={nodes.mesh_Body_mat_rubber_0.geometry}
                            material={materials.mat_rubber}
                          />
                        </group>
                      </group>
                      <group name="Pedal001" position={[-0.25, 0.84, 0.07]}>
                        <group name="mesh_Pedal001">
                          <group
                            name="Object_136"
                            position={[0.25, -1.11, 0.44]}
                          >
                            <mesh
                              name="mesh_Pedal001_mat_inside_panel_0"
                              geometry={
                                nodes.mesh_Pedal001_mat_inside_panel_0.geometry
                              }
                              material={materials.mat_inside_panel}
                            />
                            <mesh
                              name="mesh_Pedal001_mat_salon_0"
                              geometry={
                                nodes.mesh_Pedal001_mat_salon_0.geometry
                              }
                              material={materials.mat_salon}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="Pedal002" position={[-0.4, 0.97, 0.36]}>
                        <group name="mesh_Pedal002">
                          <group
                            name="Object_141"
                            position={[0.4, -1.24, 0.15]}
                          >
                            <mesh
                              name="mesh_Pedal002_mat_inside_panel_0"
                              geometry={
                                nodes.mesh_Pedal002_mat_inside_panel_0.geometry
                              }
                              material={materials.mat_inside_panel}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="Pedal003" position={[-0.67, 1.05, 0.35]}>
                        <group name="mesh_Pedal_003">
                          <group
                            name="Object_145"
                            position={[0.67, -1.32, 0.16]}
                          >
                            <mesh
                              name="mesh_Pedal_003_mat_inside_panel_0"
                              geometry={
                                nodes.mesh_Pedal_003_mat_inside_panel_0.geometry
                              }
                              material={materials.mat_inside_panel}
                            />
                          </group>
                        </group>
                      </group>
                      <group
                        name="SteeringWheel"
                        position={[-0.36, 0.49, 0.63]}
                        rotation={[-0.38, 0, 0]}
                      >
                        <group name="mesh_SteeringWheel">
                          <group
                            name="Object_149"
                            position={[0.36, -0.66, -0.39]}
                            rotation={[0.38, 0, 0]}
                          >
                            <mesh
                              name="mesh_SteeringWheel_mat_inside_gauges_0"
                              geometry={
                                nodes.mesh_SteeringWheel_mat_inside_gauges_0
                                  .geometry
                              }
                              material={materials.mat_inside_gauges}
                            />
                            <mesh
                              name="mesh_SteeringWheel_mat_leather_0"
                              geometry={
                                nodes.mesh_SteeringWheel_mat_leather_0.geometry
                              }
                              material={materials.mat_leather}
                            />
                            <mesh
                              name="mesh_SteeringWheel_mat_inside_panel_0"
                              geometry={
                                nodes.mesh_SteeringWheel_mat_inside_panel_0
                                  .geometry
                              }
                              material={materials.mat_inside_panel}
                            />
                            <mesh
                              name="mesh_SteeringWheel_mat_salon_0"
                              geometry={
                                nodes.mesh_SteeringWheel_mat_salon_0.geometry
                              }
                              material={materials.mat_salon}
                            />
                          </group>
                        </group>
                      </group>
                      <group
                        name="Gauge_Temp"
                        position={[-0.5, 0.66, 0.73]}
                        rotation={[0, 0, 3.14]}
                      >
                        <group name="mesh_Gauge_Temp">
                          <group
                            name="Object_156"
                            position={[-0.5, 0.93, -0.22]}
                            rotation={[0, 0, -3.14]}
                          >
                            <mesh
                              name="mesh_Gauge_Temp_mat_inside_gauges_0"
                              geometry={
                                nodes.mesh_Gauge_Temp_mat_inside_gauges_0
                                  .geometry
                              }
                              material={materials.mat_inside_gauges}
                            />
                          </group>
                        </group>
                      </group>
                      <group
                        name="Gauge_Speed"
                        position={[-0.36, 0.66, 0.75]}
                        rotation={[0, 0, 3.14]}
                      >
                        <group name="mesh_Gauge_Speed">
                          <group
                            name="Object_160"
                            position={[-0.36, 0.93, -0.24]}
                            rotation={[0, 0, -3.14]}
                          >
                            <mesh
                              name="mesh_Gauge_Speed_mat_inside_gauges_0"
                              geometry={
                                nodes.mesh_Gauge_Speed_mat_inside_gauges_0
                                  .geometry
                              }
                              material={materials.mat_inside_gauges}
                            />
                          </group>
                        </group>
                      </group>
                      <group
                        name="Gauge_RPM"
                        position={[-0.22, 0.65, 0.73]}
                        rotation={[0, 0, 3.14]}
                      >
                        <group name="mesh_Gauge_RPM">
                          <group
                            name="Object_164"
                            position={[-0.22, 0.92, -0.22]}
                            rotation={[0, 0, -3.14]}
                          >
                            <mesh
                              name="mesh_Gauge_RPM_mat_inside_gauges_0"
                              geometry={
                                nodes.mesh_Gauge_RPM_mat_inside_gauges_0
                                  .geometry
                              }
                              material={materials.mat_inside_gauges}
                            />
                          </group>
                        </group>
                      </group>
                      <group
                        name="Gauge_Fuel"
                        position={[-0.5, 0.66, 0.73]}
                        rotation={[0, 0, 3.14]}
                      >
                        <group name="mesh_Gauge_Fuel">
                          <group
                            name="Object_168"
                            position={[-0.5, 0.93, -0.22]}
                            rotation={[0, 0, -3.14]}
                          >
                            <mesh
                              name="mesh_Gauge_Fuel_mat_inside_gauges_0"
                              geometry={
                                nodes.mesh_Gauge_Fuel_mat_inside_gauges_0
                                  .geometry
                              }
                              material={materials.mat_inside_gauges}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="BrakeDiskRL" position={[-0.77, -1.38, 0.13]}>
                        <group name="mesh_BrakeDiskRL">
                          <group name="Object_172" position={[0.77, 1.12, 0.4]}>
                            <mesh
                              name="mesh_BrakeDiskRL_mat_brakes_0"
                              geometry={
                                nodes.mesh_BrakeDiskRL_mat_brakes_0.geometry
                              }
                              material={materials.mat_brakes}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="BrakeDiskRR" position={[0.77, -1.38, 0.13]}>
                        <group name="mesh_BrakeDiskRR" position={[0.04, 0, 0]}>
                          <group
                            name="Object_176"
                            position={[-0.81, 1.12, 0.4]}
                          >
                            <mesh
                              name="mesh_BrakeDiskRR_mat_brakes_0"
                              geometry={
                                nodes.mesh_BrakeDiskRR_mat_brakes_0.geometry
                              }
                              material={materials.mat_brakes}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="BrakeDiskFR" position={[0.77, 1.48, 0.13]}>
                        <group name="mesh_BrakeDiskFR">
                          <group
                            name="Object_180"
                            position={[-0.77, -1.75, 0.38]}
                          >
                            <mesh
                              name="mesh_BrakeDiskFR_mat_brakes_0"
                              geometry={
                                nodes.mesh_BrakeDiskFR_mat_brakes_0.geometry
                              }
                              material={materials.mat_brakes}
                            />
                          </group>
                        </group>
                      </group>
                      <group name="BrakeDiskFL" position={[-0.77, 1.48, 0.13]}>
                        <group name="mesh_BrakeDiskFL">
                          <group
                            name="Object_184"
                            position={[0.77, -1.75, 0.38]}
                          >
                            <mesh
                              name="mesh_BrakeDiskFL_mat_brakes_0"
                              geometry={
                                nodes.mesh_BrakeDiskFL_mat_brakes_0.geometry
                              }
                              material={materials.mat_brakes}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/carModel.gltf");
